export const ADD_INGREDIENTS = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENTS = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const PURCHASE_INIT = 'PURCHASE_INIT';
export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';

export const FETCH_DATA = {
    START: 'FETCH_DATA_START',
    SUCCESS: 'FETCH_DATA_SUCCESS',
    FAIL: 'FETCH_DATA_FAIL'
};

export const AUTH = {
    START: 'AUTH_START',
    SUCCESS: 'AUTH_SUCCESS',
    FAIL: 'AUTH_FAIL',
    LOGOUT: 'AUTH_LOGOUT'
};